const key="delegacje-flota-data-v2";
const initial={trips:[],expenses:[],fuelings:[],incidents:[],notifications:[],vehicles:[{id:"demo-car",make:"Skoda",model:"Octavia",registration:"DEMO 001",mileage:42150,status:"Dostępny"}]};
let data=JSON.parse(localStorage.getItem(key)||"null")||structuredClone(initial);for(const k of Object.keys(initial))if(!Array.isArray(data[k]))data[k]=structuredClone(initial[k]);
const money=new Intl.NumberFormat("pl-PL",{style:"currency",currency:"PLN"}),num=new Intl.NumberFormat("pl-PL");
const $=s=>document.querySelector(s);const save=()=>localStorage.setItem(key,JSON.stringify(data));
function esc(v=""){const n=document.createElement("span");n.textContent=String(v);return n.innerHTML}
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2400)}
function notify(m){data.notifications.unshift({id:crypto.randomUUID(),message:m,at:new Date().toISOString()});save()}
function vname(id){const v=data.vehicles.find(x=>x.id===id);return v?`${v.make} ${v.model} — ${v.registration}`:"Nieznany pojazd"}
function fileMeta(f){return f?.name?{name:f.name,size:f.size,type:f.type}:null}
function gps(){return new Promise((ok,no)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>ok({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:Math.round(p.coords.accuracy)}),no,{enableHighAccuracy:true,timeout:10000,maximumAge:0}):no(new Error("GPS unavailable")))}
function status(s){return({draft:"Zgłoszona",started:"W trasie",finished:"Zakończona"})[s]||s}
function renderSelects(){
  $("#expenseTrip").innerHTML='<option value="">Bez przypisania</option>'+data.trips.map(t=>`<option value="${t.id}">${esc(t.destination)} · ${esc(t.startDate)}</option>`).join("");
  const opts=data.vehicles.map(v=>`<option value="${v.id}">${esc(v.make)} ${esc(v.model)} — ${esc(v.registration)}</option>`).join("");$("#fuelVehicle").innerHTML=opts;$("#incidentVehicle").innerHTML=opts;
}
function render(){
  const km=data.trips.reduce((s,t)=>s+Math.max(0,(t.endOdometer||0)-(t.startOdometer||0)),0),cost=[...data.expenses,...data.fuelings].reduce((s,x)=>s+Number(x.amount||0),0),open=data.incidents.filter(x=>x.status!=="closed");
  $("#tripsCount").textContent=data.trips.length;$("#distanceCount").textContent=`${num.format(km)} km`;$("#expenseCount").textContent=money.format(cost);$("#incidentCount").textContent=open.length;
  const tl=$("#tripsList");tl.className=data.trips.length?"items":"empty-state";tl.innerHTML=data.trips.length?data.trips.map(t=>{const a=t.status==="draft"?`<button class="mini-button" data-trip-action="start" data-id="${t.id}">Start</button>`:t.status==="started"?`<button class="mini-button danger" data-trip-action="finish" data-id="${t.id}">Zakończ</button>`:"";const k=t.status==="finished"?` · ${num.format(Math.max(0,(t.endOdometer||0)-(t.startOdometer||0)))} km`:"";return`<div class="item"><span class="item-icon">✈</span><div><strong>${esc(t.destination)}</strong><small>${esc(t.startDate)} – ${esc(t.endDate)} · ${esc(t.transport)}${k}</small></div><span class="pill status-${t.status}">${status(t.status)}</span>${a}</div>`}).join(""):"Nie masz jeszcze delegacji.";
  $("#vehiclesList").innerHTML=data.vehicles.length?data.vehicles.map(v=>`<div class="item"><span class="item-icon">🚗</span><div><strong>${esc(v.make)} ${esc(v.model)}</strong><small>${esc(v.registration)} · ${num.format(v.mileage||0)} km</small></div><span class="pill">${esc(v.status||"Dostępny")}</span></div>`).join(""):"Brak pojazdów.";
  const all=[...data.expenses.map(x=>({...x,type:"cost"})),...data.fuelings.map(x=>({...x,type:"fuel",category:"Paliwo"}))].sort((a,b)=>(b.createdAt||"").localeCompare(a.createdAt||"")),el=$("#expensesList");el.className=all.length?"items":"empty-state";el.innerHTML=all.length?all.map(x=>`<div class="item"><span class="item-icon">${x.type==="fuel"?"⛽":"⌁"}</span><div><strong>${esc(x.category)}</strong><small>${esc(x.date||x.createdAt?.slice(0,10)||"")}${x.note?` · ${esc(x.note)}`:""}${x.document?.name?` · 📎 ${esc(x.document.name)}`:""}</small></div><strong>${money.format(Number(x.amount||0))}</strong></div>`).join(""):"Brak kosztów.";
  const il=$("#incidentsList");il.className=open.length?"items":"empty-state";il.innerHTML=open.length?open.map(x=>`<div class="item"><span class="item-icon">⚠</span><div><strong>${esc(x.category)}</strong><small>${esc(vname(x.vehicleId))} · ${esc(x.description)}${x.unsafe?" · NIE JECHAĆ":""}</small></div></div>`).join(""):"Brak otwartych zgłoszeń.";
  const nl=$("#notificationsList");nl.className=data.notifications.length?"items":"empty-state";nl.innerHTML=data.notifications.length?data.notifications.map(n=>`<div class="item"><span class="item-icon">🔔</span><div><strong>${esc(n.message)}</strong><small>${new Date(n.at).toLocaleString("pl-PL")}</small></div></div>`).join(""):"Brak powiadomień.";const b=$("#notificationBadge");b.textContent=data.notifications.length;b.classList.toggle("hidden",!data.notifications.length);renderSelects();bindTripActions();
}
function bindTripActions(){document.querySelectorAll("[data-trip-action]").forEach(b=>b.onclick=()=>{const t=data.trips.find(x=>x.id===b.dataset.id),a=b.dataset.tripAction,f=$("#tripActionForm");if(!t)return;f.tripId.value=t.id;f.action.value=a;f.odometer.min=a==="finish"?Number(t.startOdometer||0):0;$("#tripActionTitle").textContent=`${a==="start"?"Rozpocznij":"Zakończ"}: ${t.destination}`;$("#tripActionSubmit").textContent=a==="start"?"Rozpocznij delegację":"Zakończ delegację";$("#tripActionModal").showModal()})}
document.querySelectorAll("[data-open-modal]").forEach(b=>b.onclick=()=>$("#"+b.dataset.openModal).showModal());document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());
$("#notificationsButton").onclick=()=>$("#notificationsModal").showModal();$("#clearNotifications").onclick=()=>{data.notifications=[];save();render()};
$("#tripForm").onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));data.trips.unshift({...f,id:crypto.randomUUID(),status:"draft",createdAt:new Date().toISOString()});notify(`Utworzono delegację do: ${f.destination}`);save();render();e.currentTarget.closest("dialog").close();e.currentTarget.reset();toast("Delegacja została zapisana.")};
$("#tripActionForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),t=data.trips.find(x=>x.id===f.get("tripId")),a=f.get("action"),odo=Number(f.get("odometer"));if(!t)return;if(a==="finish"&&odo<Number(t.startOdometer||0))return toast("Końcowy licznik nie może być niższy.");let pos=null;if(f.get("useGps"))try{pos=await gps()}catch{toast("GPS niedostępny — zapisuję bez lokalizacji.")}if(a==="start"){Object.assign(t,{status:"started",startedAt:new Date().toISOString(),startOdometer:odo,startGps:pos});notify(`Rozpoczęto delegację: ${t.destination}`)}else{Object.assign(t,{status:"finished",finishedAt:new Date().toISOString(),endOdometer:odo,endGps:pos});notify(`Zakończono delegację: ${t.destination}`)}save();render();e.currentTarget.closest("dialog").close();e.currentTarget.reset();toast("Zapisano przebieg delegacji.")};
$("#expenseForm").onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),file=e.currentTarget.elements.document.files[0];data.expenses.unshift({id:crypto.randomUUID(),tripId:fd.get("tripId"),category:fd.get("category"),amount:Number(fd.get("amount")),date:fd.get("date"),note:fd.get("note"),document:fileMeta(file),createdAt:new Date().toISOString()});notify("Dodano koszt do rozliczenia");save();render();e.currentTarget.closest("dialog").close();e.currentTarget.reset();$("#documentInfo").textContent="";toast("Koszt został dodany.")};
$("#expenseForm").elements.document.onchange=e=>{const f=e.target.files[0];$("#documentInfo").textContent=f?`Wybrano: ${f.name} (${Math.round(f.size/1024)} KB)`:""};
$("#fuelForm").onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),v=data.vehicles.find(x=>x.id===fd.get("vehicleId")),m=Number(fd.get("odometer"));if(v&&m<Number(v.mileage||0))return toast("Nowy przebieg nie może być niższy.");if(v)v.mileage=m;data.fuelings.unshift({id:crypto.randomUUID(),vehicleId:fd.get("vehicleId"),liters:Number(fd.get("liters")),amount:Number(fd.get("amount")),odometer:m,station:fd.get("station"),document:fileMeta(e.currentTarget.elements.document.files[0]),createdAt:new Date().toISOString()});notify(`Dodano tankowanie: ${vname(fd.get("vehicleId"))}`);save();render();e.currentTarget.closest("dialog").close();e.currentTarget.reset();toast("Tankowanie zapisane.")};
$("#vehicleForm").onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));data.vehicles.push({id:crypto.randomUUID(),make:f.make,model:f.model,registration:f.registration,mileage:Number(f.mileage),status:"Dostępny"});save();render();e.currentTarget.closest("dialog").close();e.currentTarget.reset();toast("Pojazd dodany.")};
$("#incidentForm").onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),unsafe=fd.get("unsafe")==="on",v=data.vehicles.find(x=>x.id===fd.get("vehicleId"));if(v&&unsafe)v.status="NIE UŻYWAĆ";data.incidents.unshift({id:crypto.randomUUID(),vehicleId:fd.get("vehicleId"),category:fd.get("category"),description:fd.get("description"),unsafe,status:"open",createdAt:new Date().toISOString()});notify(`Nowe zgłoszenie floty: ${fd.get("category")}`);save();render();e.currentTarget.closest("dialog").close();e.currentTarget.reset();toast("Zgłoszenie zapisane.")};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");let installPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("#installButton").classList.remove("hidden")});$("#installButton").onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("#installButton").classList.add("hidden")};render();