<?php
declare(strict_types=1);

require __DIR__ . '/_bootstrap.php';
if (app_mode() !== 'production') {
    http_response_code(503);
    exit('Moduł kosztów wymaga APP_MODE=production.');
}
$userId = require_production_user();
$roles = $_SESSION['roles'] ?? [];
$csrf = (string) ($_SESSION['csrf_token'] ?? '');
?>
<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#111827"><title>Koszty — Delegacje + Flota</title><link rel="manifest" href="./manifest.webmanifest"><link rel="stylesheet" href="./assets/css/app.css"><style>.expense-form{display:grid;gap:12px}.expense-form input,.expense-form textarea,.expense-form select{box-sizing:border-box;width:100%;padding:12px;border:1px solid #d1d5db;border-radius:12px}.expense-list{display:grid;gap:12px}.expense-meta{display:flex;gap:8px;flex-wrap:wrap;color:#64748b;font-size:.88rem}.expense-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.expense-actions button{border:0;border-radius:10px;padding:10px 12px;background:#111827;color:#fff}.expense-actions button.danger{background:#fee2e2;color:#991b1b}.expense-actions a{padding:10px 12px}.hidden{display:none!important}.expense-tabs{display:flex;gap:8px;margin-bottom:14px}.expense-tabs button{border:0;border-radius:999px;padding:10px 14px;background:#eef2f7}.expense-tabs button.active{background:#111827;color:#fff}</style></head>
<body><div class="app-shell"><header class="page-header"><a class="back-link" href="./">←</a><div><p class="eyebrow">Księgowość</p><h1>Koszty i dokumenty</h1></div></header><main class="content"><div class="expense-tabs"><button class="active" id="expensesListTab" type="button">Koszty</button><button id="expensesNewTab" type="button">+ Dodaj</button></div><div id="expenseMessage" class="alert" hidden></div><section id="expensesList" class="expense-list" aria-live="polite"><article class="card">Ładowanie…</article></section><section id="expenseNew" class="hidden"><form id="expenseForm" class="card expense-form" enctype="multipart/form-data"><label>Delegacja<select id="expenseDelegation" name="delegation_id"><option value="">Bez powiązania</option></select></label><label>Kategoria<select name="category"><option value="fuel">Paliwo</option><option value="hotel">Nocleg</option><option value="parking">Parking</option><option value="toll">Opłata drogowa</option><option value="meal">Posiłek</option><option value="other">Inne</option></select></label><div class="form-grid"><label>Kwota<input name="amount" type="number" min="0.01" max="1000000" step="0.01" inputmode="decimal" required></label><label>Waluta<select name="currency"><option>PLN</option><option>EUR</option><option>USD</option><option>GBP</option></select></label></div><label>Data kosztu<input name="expense_date" type="date" value="<?= h(date('Y-m-d')) ?>" required></label><label>Opis<textarea name="description" rows="4" maxlength="2000" placeholder="Opcjonalny opis kosztu"></textarea></label><label class="file-drop">📷 Paragon / dokument<input name="document" type="file" accept="image/jpeg,image/png,application/pdf" capture="environment"><small>JPG, PNG lub PDF, maksymalnie 10 MB</small></label><button class="primary-btn dark-btn full" type="submit">Zapisz koszt</button></form></section></main><nav class="bottom-nav" aria-label="Nawigacja główna"><a href="./"><span>⌂</span><small>Start</small></a><a href="./mobile.php"><span>🧳</span><small>Delegacje</small></a><a href="./fleet.php"><span>🚗</span><small>Flota</small></a><a href="./profile.php"><span>👤</span><small>Profil</small></a></nav></div><script>window.DELEGACJE_EXPENSES_BOOT={csrf:<?= json_encode($csrf) ?>,roles:<?= json_encode(array_values($roles)) ?>,userId:<?= (int) $userId ?>};</script><script src="./assets/js/expenses-api.js"></script><script src="./assets/js/pwa.js"></script></body></html>
